export interface LiveShow {
  slug: string;
  artist: string;
  date: string | null;
  dateLabel: string;
  venue: string;
  city?: string;
  context?: string;
  companions?: string;
  summary: string;
  notes: string[];
  tags: string[];
}

export const liveShows: LiveShow[] = [
  {
    slug: "vulfpeck-o2-arena-2026",
    artist: "Vulfpeck",
    date: "2026-07-08",
    dateLabel: "8 July 2026",
    venue: "O2 Arena",
    city: "London",
    summary: "Bucket-list show that lived up to expectations, despite a distant seat and rough low-end sound.",
    notes: [
      "Seat was in the middle and quite far back, so most of the detail came through the screens.",
      "Bass and kick sounded terrible, probably because of the room size, but the rest of the band sounded good.",
      "They played most of the classics and the energy was great.",
      "No Theo Katzman, but the Jeffrey guy covered the spot well.",
      "Loved the show, though sitting down with a quiet crowd made it hard to dance.",
    ],
    tags: ["funk", "bucket list", "arena"],
  },
  {
    slug: "snarky-puppy-jardin-botanico-2026",
    artist: "Snarky Puppy",
    date: "2026-07-04",
    dateLabel: "4 July 2026",
    venue: "Jardin Botanico",
    summary: "Huge-sounding set from an absurdly good band, with Michael League conducting and Lingus saved for the encore.",
    notes: [
      "Watched from pista near the back and it still sounded massive.",
      "Michael League was conducting; this was not the biggest lineup, with three winds, percussion and drums, two keys/synth/organ/clavinet players, violin, and electric guitar.",
      "The crowd moved more than usual, with many older heads around.",
      "They played a lot of the recent album plus classics, and left Lingus for the encore.",
      "Nate Smith's keyboardist came out for the Lingus solo. There was also an extremely impressive clavinet solo.",
      "One of the best concerts in a long while.",
    ],
    tags: ["jazz fusion", "encore", "great band"],
  },
  {
    slug: "nate-smith-jardin-botanico-2026",
    artist: "Nate Smith",
    date: "2026-07-04",
    dateLabel: "4 July 2026",
    venue: "Jardin Botanico",
    companions: "Ainhoa",
    summary: "Front-row set in intense heat, with great playing and a keyboard setup that stood out.",
    notes: [
      "Went with Ainhoa. It was very hot, but we got front row.",
      "Most of the audience was older and seemed to be there for Snarky Puppy rather than Nate.",
      "He played great, though not quite amazing.",
      "The bassist was really good, but hard to hear properly from our position because we were too far upfront.",
      "Sax player was nice too, using pedals and delays.",
      "Keys were the coolest part, just a controller setup.",
    ],
    tags: ["jazz", "front row", "hot"],
  },
  {
    slug: "grobas-30-aniversario-playa-2026",
    artist: "Grobas 30 aniversario",
    date: "2026-06-20",
    dateLabel: "20 June 2026",
    venue: "Playa",
    companions: "Markos, Mata, Juanka, Diego",
    summary: "Fun vinyl-heavy anniversary night, loud and loose, with good vibes in a half-empty place.",
    notes: [
      "Went with Markos, Mata, Juanka, and Diego.",
      "Mostly vinyl through the night and loud as hell.",
      "The place was half empty and mostly older people, but the vibe was good.",
      "Stayed until close.",
    ],
    tags: ["dj", "vinyl", "friends"],
  },
  {
    slug: "black-country-new-road-sala-inn-2026",
    artist: "Black Country, New Road",
    date: "2026-06-10",
    dateLabel: "10 June 2026",
    venue: "Sala Inn",
    companions: "Ainhoa",
    summary: "Really strong playing in a bad, hot, late-running room.",
    notes: [
      "Went with Ainhoa and found friends there.",
      "The playing was really good, but the room and sound were terrible.",
      "They came out about an hour late and it was hot inside.",
      "Liked the instrument variety: accordion, clarinet, violin, and more.",
    ],
    tags: ["indie", "bad sound", "ensemble"],
  },
  {
    slug: "macromassa-50-aniversario-2026",
    artist: "Macromassa 50 aniversario",
    date: "2026-05-09",
    dateLabel: "9 May 2026",
    venue: "Centre Artesa Tradicionaus",
    summary: "Interesting old experimental set built around dissociative narration over beats.",
    notes: [
      "Did not really know the group's history going in.",
      "Cool and experimental, with spoken narrations over beats.",
      "Felt like it might have been the worst concert this group ever did, but it was still quite interesting.",
    ],
    tags: ["experimental", "anniversary"],
  },
  {
    slug: "barcode-sala-meteoro-2026",
    artist: "Barcode",
    date: "2026-05-06",
    dateLabel: "6 May 2026",
    venue: "Sala Meteoro",
    summary: "Great sounds with city/port displacement visuals that had depth even when not fully synced to the music.",
    notes: [
      "The visuals had interesting city and port displacement aesthetics.",
      "They were not really synced with the music, but still had depth.",
      "The music was great and the sounds were extremely enjoyable, even if it did not look like he was doing much on the effects.",
    ],
    tags: ["electronic", "visuals"],
  },
  {
    slug: "flo-de-lotus-sala-meteoro-2026",
    artist: "Flo de Lotus",
    date: "2026-05-06",
    dateLabel: "6 May 2026",
    venue: "Sala Meteoro",
    summary: "Excellent first-ever show: young band, real playing, polyrhythms, improvisation, effects, and modular textures.",
    notes: [
      "Electronic-acoustic music in a great room with a great live setup.",
      "Five young musicians playing for real.",
      "Polyrhythms, improvisations, tons of effects, modular elements, and basically everything I loved.",
      "It turned out to be their first show ever, which made it even more impressive.",
    ],
    tags: ["electronic", "acoustic", "first show"],
  },
  {
    slug: "judeline-ppio-2026",
    artist: "Judeline",
    date: "2026-05-01",
    dateLabel: "1 May 2026",
    venue: "Ppio",
    summary: "Good public concert, overcrowded and mixed only okay, but with dancers and live instruments adding a lot.",
    notes: [
      "There were way too many people.",
      "Had to get out and then struggled to get back in.",
      "The mix was not great.",
      "There were dancers doing cool stuff around the stage, plus live instruments.",
    ],
    tags: ["pop", "public concert", "crowded"],
  },
  {
    slug: "charlie-heeb-mash-2026",
    artist: "Charlie Heeb",
    date: "2026-04-26",
    dateLabel: "26 April 2026",
    venue: "Mash",
    summary: "Unexpected late follow-up show with a rock/blues vibe in a cool place.",
    notes: [
      "The drummer and bassist from Jacob Khalil's concert told us they were playing somewhere else later.",
      "Rock and blues vibe.",
      "Cool place and a fun night.",
    ],
    tags: ["rock", "blues", "aftershow"],
  },
  {
    slug: "jacob-khalil-the-jazz-club-2026",
    artist: "Jacob Khalil",
    date: "2026-04-26",
    dateLabel: "26 April 2026",
    venue: "The Jazz Club",
    summary: "Stumbled into a fun Vulfpeck-like jazz club set.",
    notes: ["Found the place by chance.", "Vulfpeck-like feel and a fun show."],
    tags: ["jazz", "funk", "stumbled upon"],
  },
  {
    slug: "eprom-g-jones-sneaky-petes",
    artist: "Eprom b2b G Jones",
    date: null,
    dateLabel: "Date not noted",
    venue: "Sneaky Pete's",
    city: "Edinburgh",
    summary: "Fun bass-heavy night right after landing in Edinburgh.",
    notes: [
      "Went there right after landing in Edinburgh.",
      "Cool music in a rough little club setting.",
      "A fun night.",
    ],
    tags: ["electronic", "club", "edinburgh"],
  },
  {
    slug: "tristan-air-jazz-band-don-giorgiio-2026",
    artist: "Tristan and the Air Jazz Band",
    date: "2026-03-07",
    dateLabel: "7 March 2026",
    venue: "Don Giorgiio",
    companions: "Alexo",
    summary: "Short, intense, funky set with strong ideas and imperfect execution.",
    notes: [
      "Went with Alexo and someone else.",
      "Tristan had many of the right ideas; it got funky and had aura.",
      "Execution was a bit lacking.",
      "Roy Borland played guitar and random instruments, the bass player was good, and Tristan played piano, computer, and sang.",
      "Sound was kind of bad, though it could maybe be argued as an artistic choice.",
    ],
    tags: ["jazz", "funk", "experimental"],
  },
  {
    slug: "elijah-fox-don-giorgiio-2026",
    artist: "Elijah Fox",
    date: "2026-01-24",
    dateLabel: "24 January 2026",
    venue: "Don Giorgiio",
    companions: "Alexo",
    summary: "Great solo-feeling set with excellent playing and delay/crystallizer textures.",
    notes: [
      "Went with Alexo.",
      "He played incredibly well.",
      "Used a Nord 3 and a multi-FX pedal.",
      "Did a lot with delay and crystallizer-style effects.",
    ],
    tags: ["keys", "effects", "jazz"],
  },
  {
    slug: "mira-2025-amnesia-scanner",
    artist: "Amnesia Scanner",
    date: "2025-11-08",
    dateLabel: "MIRA 2025, Saturday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Really hard and really good, with fog-heavy visuals that were hard to see but still cool.",
    notes: [
      "Very hard set and really good.",
      "The visuals were difficult because there was a lot of fog, but the overall effect was cool.",
    ],
    tags: ["electronic", "festival", "hard"],
  },
  {
    slug: "mira-2025-oneohtrix-point-never",
    artist: "Oneohtrix Point Never",
    date: "2025-11-08",
    dateLabel: "MIRA 2025, Saturday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Good but uneven musically, with Freeka Tet's CRT/simulation visual system carrying a lot of the show.",
    notes: [
      "First half was a bit underwhelming, then the music went crazy.",
      "Visuals carried the set: Freeka Tet had a simulation he could play with, changing textures while filming a CRT and physically moving the camera around.",
      "Mind-bending visual setup.",
    ],
    tags: ["electronic", "visuals", "festival"],
  },
  {
    slug: "mira-2025-flying-lotus",
    artist: "Flying Lotus",
    date: "2025-11-08",
    dateLabel: "MIRA 2025, Saturday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "A letdown: bad mix, weak visuals, and new material that did not land, with a good You're Dead! remix near the end.",
    notes: [
      "Music sounded badly mixed.",
      "Visuals were terrible: VJ loops on two screens, one transparent in front and one smaller screen in the back, completely out of sync.",
      "He had aura, but the newer material mostly did not work for me and drifted into Ibiza-house territory at points.",
      "Cool remix of You're Dead! near the end.",
    ],
    tags: ["electronic", "festival", "disappointing"],
  },
  {
    slug: "mira-2025-blawan",
    artist: "Blawan",
    date: "2025-11-08",
    dateLabel: "MIRA 2025, Saturday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Extremely serious full-live set with strong visuals and consistent feedback.",
    notes: [
      "Full live set that went hard.",
      "Visuals were good and the feedback was consistent.",
      "Everyone liked him; probably the highest point of the night.",
    ],
    tags: ["techno", "live", "festival"],
  },
  {
    slug: "mira-2025-ali-sethi-nicolas-jaar",
    artist: "Ali Sethi + Nicolas Jaar",
    date: "2025-11-07",
    dateLabel: "MIRA 2025, Friday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Only caught the second half, but the piano and singing were impressive and politically conscious.",
    notes: [
      "Watched only the second half.",
      "Mostly piano with impressive singing.",
      "They brought out Palestinian singers too, and it felt very conscious.",
    ],
    tags: ["festival", "piano", "voice"],
  },
  {
    slug: "mira-2025-aya-mfo",
    artist: "aya + MFO",
    date: "2025-11-07",
    dateLabel: "MIRA 2025, Friday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Chaotic and entertaining from the front rows, with great music and only okay mixing/lasers.",
    notes: [
      "Did not disappoint, though the mixing was not great.",
      "Watched from the first rows.",
      "She broke a mic, threw it to the public, then asked for another one.",
      "Music was great, and she shit-talked and talked crazy at points.",
      "Lasers were cool but a bit underwhelming.",
    ],
    tags: ["electronic", "festival", "chaotic"],
  },
  {
    slug: "mira-2025-floating-points",
    artist: "Floating Points + Hamill Industries",
    date: "2025-11-07",
    dateLabel: "MIRA 2025, Friday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Main event of the day: genuinely live music with liquid visuals, watched from farther back while already tired.",
    notes: [
      "Watched from kind of far away.",
      "Really good, with actual live music and liquid VJ work.",
      "Sadly I was already quite tired.",
    ],
    tags: ["electronic", "live", "visuals", "festival"],
  },
  {
    slug: "mira-2025-john-maus",
    artist: "John Maus",
    date: "2025-11-07",
    dateLabel: "MIRA 2025, Friday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Interesting, though I did not watch much of it.",
    notes: ["Liked what I saw, but only watched a short part of the set."],
    tags: ["festival", "synth"],
  },
  {
    slug: "mira-2025-los-thuthanaka",
    artist: "Los Thuthanaka",
    date: "2025-11-07",
    dateLabel: "MIRA 2025, Friday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Original Andean-Latin electronic set that slapped before leaving for Floating Points.",
    notes: [
      "Original Latin/Andean electronic music that hit hard.",
      "Had to leave after a while to catch Floating Points.",
    ],
    tags: ["electronic", "latin", "festival"],
  },
  {
    slug: "mira-2025-lechuga-zafiro-verraco",
    artist: "Lechuga Zafiro and Verraco",
    date: "2025-11-07",
    dateLabel: "MIRA 2025, Friday",
    venue: "MIRA Festival",
    city: "Barcelona",
    context: "MIRA 2025",
    summary: "Best of Friday: relentless hectic music with funny internet-coded visuals.",
    notes: [
      "By far the best of the day.",
      "Hectic music that did not stop for a second and somehow kept me alive.",
      "Internet-coded visuals were very funny.",
      "Mata was dumbfounded too.",
    ],
    tags: ["electronic", "festival", "favorite"],
  },
  {
    slug: "thundercat-pulse-of-gaia-2025",
    artist: "Thundercat",
    date: "2025-09-20",
    dateLabel: "20 September 2025",
    venue: "Pulse of Gaia Fest",
    summary: "Maybe the best bass player alive, sounding much bigger live than on record with only drums and keys behind him.",
    notes: [
      "Extremely good and funny.",
      "Came with only a drummer and a keyboardist and still sounded full.",
      "He was playing bass, melody, and chords at the same time.",
      "Played Spain in Spain, and the set was full of references.",
      "His music live is ten times better than the recorded songs.",
      "Played some very new material that sounded great. Shout out Louis Cole.",
    ],
    tags: ["bass", "festival", "favorite"],
  },
  {
    slug: "gorillaz-pulse-of-gaia-2025",
    artist: "Gorillaz",
    date: "2025-09-20",
    dateLabel: "20 September 2025",
    venue: "Pulse of Gaia Fest",
    summary: "Great long set with a lot of guests and classic songs, though I was tired by then.",
    notes: [
      "The set was very long and I was already tired.",
      "They brought out a bunch of people, including rappers and Trueno, though not Thundercat.",
      "Damon has a lot of classic songs.",
    ],
    tags: ["festival", "classic songs"],
  },
  {
    slug: "oscar-jerome-garufa",
    artist: "Oscar Jerome",
    date: null,
    dateLabel: "Date not noted",
    venue: "Garufa",
    summary: "Honestly great show with excellent musicians and a frontperson who felt one of a kind.",
    notes: ["Really liked it.", "Great musicians, and Oscar Jerome is one of a kind."],
    tags: ["jazz", "soul", "guitar"],
  },
];
